# Generated by Django 5.2.7 on 2025-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_seat_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
