# Generated by Django 5.2.7 on 2025-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
